name: Publish to Docker Hub And Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pilue/code-server-azure:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Update image tag on the Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cs2-pilue'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          images: 'pilue/code-server-azure:${{ github.sha }}'